services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - POSTGRES_URL=$POSTGRES_URL
    networks:
      - bear

networks:
  bear:
    external: true