site_name: Backend for Embedded Academic Resources (BEAR)
site_url: https://uw-madison-dsi.github.io/bear
site_description: An open-source framework that simplifies embedding integration for academic use, enabling semantic search for experts and interaction with digital twins.
repo_url: https://github.com/uw-madison-dsi/bear
repo_name: uw-madison-dsi/bear

theme:
  name: shadcn
  features:
    - navigation.instant
    - navigation.tabs
    - search.highlight
    - search.suggest
    - navigation.top
    - content.code.copy
extra_css:
  - assets/css/overrides.css
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            filters:
              - "!^_"  # exclude private members
  - mkdocs-jupyter:
      include_source: true
      execute: false
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Usage: api_usage.ipynb
  - Developer Reference:
      - API: reference/api.md
      - Config: reference/config.md
      - Crawler: reference/crawler.md
      - Database: reference/db.md
      - Embedding: reference/embedding.md
      - Ingest: reference/ingest.md
      - Model: reference/model.md
      - Search: reference/search.md
      - Documentation Guide: reference/docs.md
  - Examples:
      - Embedder: examples/embedder.ipynb

markdown_extensions:
  - admonition
  - codehilite:
      use_pygments: true
  - toc:
      permalink: "🔗"
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
